global class InstantAddressSection {
    global string collapsed { get; set; }
    global string columns { get; set; }
    global string heading { get; set; }
    global string layoutSectionId { get; set; }
    global string parentLayoutId { get; set; }
    global string rows { get; set; }
    global string tabOrder { get; set; }
    global string useCollapsibleSection { get; set; }
    global string useHeading { get; set; }
    global List<InstantAddressRow> layoutRows { get; set; }
}