public class InstantAddressBatch {
 /*
     public Map<String, List<SelectOption>> getFieldOptionsMap() {
    
        Map<String, List<SelectOption>> m = new Map<String, List<SelectOption>>();
    
        SObjectField[] fields = Account.SObjectType.getDescribe().fields.getMap().values();
    
        for (SObjectType f : fields) {
            List<SelectOption> options = new List<SelectOption>();
            for (PicklistEntry pe : t.getDescribe().getPicklistValues()) {
                options.add(new SelectOption(pe.getValue(), pe.getLabel()));
            }
            m.put(String.valueOf(t), options);
        }
    
        return m;
    }
    */
    
//  public class 
}